### ISSUE TITLE
맨데이 계산

### ISSUE THREAD

**Issue by hj78080** [CSID-DGU/ASCP#102]
데드헤드로 모기지로 못돌아온 페어링은 후에 모기지로 돌아오는 것 고려하여
최종 맨데이 계산할 수 있어야함

_Originally posted by @hj78080 in https://github.com/CSID-DGU/ASCP/issues/101#issuecomment-2211581543_

**Comment by wendyunji** [comment]
### Solver 운영 관련
- [ ] manday 계산하는 일수가 수정되어야 함.
- [ ] Brief & Debrief가 반영 되어야 한다.

### 입출력 관련
- [ ] 마지막에 터미널에 출력되는 부분을 삭제 혹은 수정
- [ ] pairing type option user input을 우선적으로 받을 수 있도록 수정할 것
